### PR TITLE
[CAD-2169] Expose API types in a separate package

### PR DESCRIPTION
**Pull request by ksaric**
https://jira.iohk.io/browse/CAD-2169

Original PR by @hasufell.
Rebased, fixed Cabal build, fixed tests and some minor things.

Note that running tests with Stack now requires:
```
stack test --fast -j`nproc` --flag 'smash:testing-mode' --flag 'smash-servant-types:testing-mode'
```

### CODE REVIEW

**Comment by ksaric** [comment]
Addressing https://github.com/input-output-hk/smash/issues/110.

**Comment by ksaric** [comment]
This is going to be squash-merged if possible since we don't want 5 commits for a single PR.

**Comment by hasufell** [comment]
> This is going to be squash-merged if possible since we don't want 5 commits for a single PR.

That's fine. What you can do in such a case is add this to the end of the commit message (the github API does that too):

```
Co-authored-by: Julian Ospald <julian.ospald@iohk.io>
```

**Review by hasufell — APPROVED** [review]
Looks good

**Comment by ksaric** [comment]
I have no idea why this is failing, my attempts at fixing the Nix thingies fail.

**Comment by jbgi** [comment]
The nix issue was that in `haskell.nix`, the flags were set only for the smash package but not for the new package.
I added a new `smash-exe-testing` nix target to keep the normal binary (withing testing flag) as default for production.

**Review by jbgi — APPROVED** [review]

**Pull request merged**
