### PR TITLE
[CAD-2177] smash should work also with pool_ids in Bech32 format.

### PR DESCRIPTION
**Pull request by ksaric**
https://jira.iohk.io/browse/CAD-2177

The API is backward compatible so we don't have to bump up the API version.
Example with regular pool id:
```
$> curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/errors/fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38 | jq .

[
  {
    "time": "23.11.2020. 08:30:01",
    "retryCount": 0,
    "poolHash": "93cf2f2fead6c419ccaae1a41f0786de4b9daefea7074d7bda3d288e76e20a97",
    "cause": "HTTP Exception from poolId fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38' when fetching metadata from 'https://explorer.shelley-qa.dev.cardano.org/p/3.json' resulted in : InternalException (HandshakeFailed (Error_Protocol (\"certificate rejected: [SelfSigned]\",True,CertificateUnknown)))",
    "poolId": "fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38",
    "utcTime": "1606120201.318317s"
  },
  {
    "time": "23.11.2020. 08:30:19",
    "retryCount": 0,
    "poolHash": "93cf2f2fead6c419ccaae1a41f0786de4b9daefea7074d7bda3d288e76e20a97",
    "cause": "HTTP Exception from poolId fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38' when fetching metadata from 'https://explorer.shelley-qa.dev.cardano.org/p/3.json' resulted in : InternalException (HandshakeFailed (Error_Protocol (\"certificate rejected: [SelfSigned]\",True,CertificateUnknown)))",
    "poolId": "fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38",
    "utcTime": "1606120219.796256s"
  }
]
```
With bech32:
```
$> curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/errors/pool1ljq292q5xwz8t3ehmaw3c5p9xprv3szwkdnrxd40004ns6dy8v0 | jq . 

[
  {
    "time": "23.11.2020. 08:30:01",
    "retryCount": 0,
    "poolHash": "93cf2f2fead6c419ccaae1a41f0786de4b9daefea7074d7bda3d288e76e20a97",
    "cause": "HTTP Exception from poolId fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38' when fetching metadata from 'https://explorer.shelley-qa.dev.cardano.org/p/3.json' resulted in : InternalException (HandshakeFailed (Error_Protocol (\"certificate rejected: [SelfSigned]\",True,CertificateUnknown)))",
    "poolId": "fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38",
    "utcTime": "1606120201.318317s"
  },
  {
    "time": "23.11.2020. 08:30:19",
    "retryCount": 0,
    "poolHash": "93cf2f2fead6c419ccaae1a41f0786de4b9daefea7074d7bda3d288e76e20a97",
    "cause": "HTTP Exception from poolId fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38' when fetching metadata from 'https://explorer.shelley-qa.dev.cardano.org/p/3.json' resulted in : InternalException (HandshakeFailed (Error_Protocol (\"certificate rejected: [SelfSigned]\",True,CertificateUnknown)))",
    "poolId": "fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38",
    "utcTime": "1606120219.796256s"
  }
]
```

### CODE REVIEW

**Comment by ksaric** [comment]
bors try

**Comment by ksaric** [comment]
What is left is the missing implementation from the request body `PATCH`.

**Comment by ksaric** [comment]
> What is left is the missing implementation from the request body `PATCH`.

Will fix in the next PR.

**Comment by ArturWieczorek** [comment]
Works, checked on `shelley-qa` with:

```sql
shelleyqa=# select * from pool_hash where hash_raw ='\x0f82d55b5a5b8a1f103e03b59bd2754cd900efed3e0d62137c6edcb9';
 id |                          hash_raw                          |                           view                           
----+------------------------------------------------------------+----------------------------------------------------------
  6 | \x0f82d55b5a5b8a1f103e03b59bd2754cd900efed3e0d62137c6edcb9 | pool1p7pd2k66tw9p7yp7qw6eh5n4fnvspmld8cxkyymudmwtjgl042l
(1 row)
```


`curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/errors/0f82d55b5a5b8a1f103e03b59bd2754cd900efed3e0d62137c6edcb9`

and 

`curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/errors/pool1p7pd2k66tw9p7yp7qw6eh5n4fnvspmld8cxkyymudmwtjgl042l`

Same content is being returned.

**Pull request merged**
