### PR TITLE
Add Bors

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by jbgi** [comment]
bors try

**Comment by jbgi** [comment]
bors retry

**Comment by jbgi** [comment]
bors abort

**Comment by jbgi** [comment]
bors try

**Comment by disassembler** [comment]
bors ping

**Comment by disassembler** [comment]
bors try-

**Comment by disassembler** [comment]
bors try

**Comment by disassembler** [comment]
bors try

**Comment by disassembler** [comment]
bors try-

**Comment by disassembler** [comment]
bors try

**Pull request closed without merging**
