### PR TITLE
Two follow-up fixes

### PR DESCRIPTION
**Pull request by hasufell**
We missed a build failure when testing mode is enabled. I also added a way to disable cardano-db-sync dependency, which is important for the wallet.

### CODE REVIEW

**Review by ksaric — CHANGES_REQUESTED** [review]
You are correct about the fix, but let's not add any more flags in. Just fix the imports, for now, any additional changes can be addressed if need be, there is no harm in having that option available to the user.

**Comment by hasufell** [comment]
> You are correct about the fix, but let's not add any more flags in. Just fix the imports, for now, any additional changes can be addressed if need be, there is no harm in having that option available to the user.

I can't follow. I currently can't integrate with SMASH without this flag.

**Review by ksaric — APPROVED** [review]
I still don't understand why. In the future, please open up an issue describing why you need the changes first, then we discuss, then you can open up a PR.
I presume you don't want to have `cardano-db-sync` as a dependency, but that doesn't mean you can't integrate against it.
Merging this for now, but I don't like adding many flags since the combination of the flags will explode and will be hard to track (compile) errors we get, like we had.

**Comment by hasufell** [comment]
>  I presume you don't want to have cardano-db-sync as a dependency, but that doesn't mean you can't integrate against it.

I can't, see https://github.com/input-output-hk/cardano-db-sync/pull/372

The maintainer thinks I shouldn't even do that, nor use SMASH.

**Pull request merged**
