### PR TITLE
Release 1.3.0.

### PR DESCRIPTION
**Pull request by ksaric**
Directly depends on https://github.com/input-output-hk/smash/pull/127, the PRs from the changelog contain the info about how to test them.

Also important to note that it depends on `cardano-db-sync` 7.1.

PRs:
- https://github.com/input-output-hk/smash/pull/112
- https://github.com/input-output-hk/smash/pull/122
- https://github.com/input-output-hk/smash/pull/123
- https://github.com/input-output-hk/smash/pull/125
- https://github.com/input-output-hk/smash/pull/124
- https://github.com/input-output-hk/smash/pull/117
- https://github.com/input-output-hk/smash/pull/119
- https://github.com/input-output-hk/smash/pull/121

### CODE REVIEW

**Comment by ksaric** [comment]
bors try

**Comment by ksaric** [comment]
bors try

**Comment by ksaric** [comment]
bors try

**Comment by ksaric** [comment]
Try harder.

**Comment by ksaric** [comment]
There is a build failure, might be the Nix setup:
```
machine # [  131.262695] r3vbmllklqyr77ji597s7d8li7ql0pn6-smash[939]: [smash-node:Info:4] [2020-12-11 14:52:12.34 UTC] Running.
machine # [  131.262695] r3vbmllklqyr77ji597s7d8li7ql0pn6-smash[939]: [smash-node:Info:4] [2020-12-11 14:52:12.34 UTC] Running: migration-1-0000-20200610.sql
machine # [  131.262695] r3vbmllklqyr77ji597s7d8li7ql0pn6-smash[939]: psql: could not connect to server: No such file or directory
machine # [  131.262695] r3vbmllklqyr77ji597s7d8li7ql0pn6-smash[939]:   Is the server running locally and accepting
machine # [  131.262695] r3vbmllklqyr77ji597s7d8li7ql0pn6-smash[939]:   connections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?
```

**Comment by jbgi** [comment]
bors try

**Comment by jbgi** [comment]
bors try

**Comment by jbgi** [comment]
bors try

**Review by jbgi — APPROVED** [review]

**Pull request merged**
